pages:
  icon: files
  label: Pages
  path: builder_site_pages_path
  controllers: ['pages', 'documents', 'resources']
library:
  icon: stack-play
  label: Media
  path: builder_site_documents_path
  controllers: ['images']
menus:
  icon: menu
  label: Menus
  path: builder_site_menus_path
  controllers: ['menus','items']
forms:
  icon: clipboard3
  label: Forms
  path: builder_site_forms_path
  controllers: ['forms', 'submissions', 'fields']
users:
  icon: user2
  label: Users
  path: builder_site_users_path
  controllers: ['users']
  admin: true
settings:
  icon: equalizer
  label: Settings
  path: builder_site_site_settings_path
  controllers: []
  admin: true
templates:
  icon: stack
  label: Templates
  path: builder_site_templates_path
  controllers: ['templates','groups','fields','template_pages']
  admin: true
resources:
  icon: folder
  label: Resources
  path: builder_site_resource_types_path
  controllers: ['resources', 'fields', 'association_fields', 'items']
  admin: true
# errors:
#   icon: notification
#   label: Errors
#   path: builder_site_errors_path
#   controllers: ['errors']
#   admin: true
admin:
  icon: cog3
  label: Admin
  path: edit_builder_site_path
  controllers: []
  admin: true
