pages:
  icon: files
  label: Pages
  path: builder_site_pages_path
  controllers: ['pages']
page_types:
  icon: wrench
  label: Templates
  path: builder_site_templates_path
  controllers: ['templates','groups','fields','template_pages']
library:
  icon: stack-play
  label: Media
  path: builder_site_documents_path
  controllers: ['images']
forms:
  icon: clipboard3
  label: Forms
  path: builder_site_forms_path
  controllers: ['forms', 'submissions']
users:
  icon: user2
  label: Users
  path: builder_site_users_path
  controllers: ['users']
settings:
  icon: cog3
  label: Settings
  path: edit_builder_site_path
  controllers: []
