title: Hello World 123
slug: hello-world-123
templates:
  home:
    title: Home
    fields:
      subtitle:
        type: string
        label: Subtitle
      header_image:
        type: string
        label: Header Image
  about:
    title: About
    fields:
      subtitle:
        type: string
        label: Subtitle
      cheese:
        type: string
        label: What is your definition of cheese?
      body:
        label: Body
      textarea:
        type: text
        label: This is a regular textarea
      wysiwyg:
        type: wysiwyg
        label: This is a wysiwyg editor
      feature_slides:
        type: block
        template: feature
        label: These are the feature slides
  feature:
    title: Feature Slide
    block: true
    fields:
      test_field:
        label: La-dee La-dee Dah
        type: string
