# 
# Sapwood Settings
# =================
# 
# This file is for storing your personal settings to make
# Sapwood work properly for you.
# 
# Replace the values here with your config, then copy to: 
# 
#     config/sapwood.yml
# 
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
#
# If you need to use any of the values here, you can get to
# them through the SapwoodSetting class. For example, you
# can access your app title like this:
# 
#     SapwoodSetting.site.title
# 
# This file is not tracked by git, so these settings are
# only present in this file on this machine.
# 
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
#
development: &default
  site:
    title:              Sapwood             # default title for the site
    url:                ''                  # the url at which you will run this application
  design:
    colors:
      primary:          099B77              # primary color
      secondary:        34495E              # accent color (good contrast to primary)
      dark:             363636              # for fonts and some grey accents
      grey:             929E9E              # a medium or dark grey works well
      light:            FFFFFF              # used to create other accent greys
  dragonfly:
    secret:             ''                  # some random hash
    host:               ''                  # your asset host (with protocol)
  api:
    public_key:         ''                  # some random hash
  remote:
    url:                ''                  # the url of your production app (e.g. cms.example.com)
    db_backup_file:     ''                  # reference to remote backup using ssh

test:
  <<: *default

production:
  <<: *default
  mailer:
    sendgrid:           false               # use sendgrid for sending emails?
    user_name:          ''                  # email username
    password:           ''                  # email password
    domain:             ''                  # email domain
    address:            smtp.gmail.com      # smtp address
    port:               587                 # smtp port
    default_from:       ''                  # address from which to send notifications
  notifications:
    errors:
      email_prefix:     "[Sapwood ERROR] "  # prefix to email subject
      sender:           ''                  # display name and email address for email
      recipient:        ''                  # who to send error notifications to
