# 
# Taproot Settings
# =================
# 
# This file is for storing your personal settings to make Taproot work properly
# for you.
# 
# Replace the values here with your config, then copy to: 
# 
#     config/taproot.yml
# 
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
#
# If you need to use any of the values here, you can get to them through the
# TaprootSetting class. For example, you can access your aws bucket name like
# this:
# 
#     TaprootSetting.aws.bucket
# 
# This file is not tracked by git, so these settings are only present in this
# file on this machine.
# 
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
#
development: &default
  site:
    title:              Taproot     # default title for the site
  design:
    colors:
      primary:          099B77      # primary color
      secondary:        34495E      # accent color (good contrast to primary)
      dark:             363636      # for fonts and some grey accents
      grey:             929E9E      # a medium or dark grey works well
      light:            FFFFFF      # used to create other accent greys
  aws:
    access_key_id:      ''          # amazon s3 api key
    secret_access_key:  ''          # amazon s3 secret
    bucket:             ''          # amazon s3 bucket name (in us standard region)
  git:
    protocol:           https       # http(s)
    url:                ''          # git host url without protocol
    username:           ''          # your git app username
    password:           ''          # your git app password
  dragonfly:
    secret:             ''          # some random hash
  remote:
    db_backup_file:     ''          # reference to remote backup using ssh

test:
  <<: *default

production:
  <<: *default
