pages:
  icon: files
  path: builder_site_path
  controllers: ['pages']
images:
  icon: stack-play
  path: builder_site_documents_path
  controllers: ['images']
forms:
  icon: clipboard3
  path: builder_site_forms_path
  controllers: ['forms']
page_types:
  icon: wrench
  path: builder_site_page_types_path
  controllers: ['page_types']
users:
  icon: user2
  path: builder_site_users_path
  controllers: ['users']
settings:
  icon: cog3
  path: edit_builder_site_path
  controllers: []
