home:
  icon: home6
  path: builder_site_path
  controllers: ['site']
page_types:
  icon: stack
  path: builder_site_page_types_path
  controllers: ['page_types']
images:
  icon: image
  path: builder_site_images_path
  controllers: ['images']
forms:
  icon: clipboard3
  path: builder_site_forms_path
  controllers: ['forms']
users:
  icon: user2
  path: builder_site_users_path
  controllers: ['users']
settings:
  icon: cog3
  path: edit_builder_site_path
  controllers: []
