home:
  icon: home6
  path: site_path
  controllers: ['site']
page_types:
  icon: stack
  path: site_page_types_path
  controllers: ['page_types']
forms:
  icon: clipboard3
  path: site_forms_path
  controllers: ['forms']
users:
  icon: user2
  path: site_users_path
  controllers: ['users']
settings:
  icon: cog3
  path: edit_site_path
  controllers: []
